# These settings are synced to GitHub by https://probot.github.io/apps/settings/
repository:
  homepage: "https://developer.lightbend.com/start/?group=lagom"
  topics: lagom, example, example-project, sample, sample-app, jvm, microservices
  private: false
  has_issues: true
  # We don't need projects in sample projects
  has_projects: false
  # We don't need wiki in sample projects
  has_wiki: false
  has_downloads: true
  default_branch: 1.5.x
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false

teams:
  - name: core
    permission: admin
  - name: integrators
    permission: write
  - name: write-bots
    permission: write

branches:
  - name: "*"
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      # Require status checks to pass before merging
      required_status_checks:
        # The list of status checks to require in order to merge into this branch
        contexts: ["Travis CI - Branch ", "Travis CI - Pull Request", "typesafe-cla-validator"]

# Labels: tailored list of labels to be used by sample applications
labels:
  - color: f9d0c4
    name: "closed:declined"
  - color: f9d0c4
    name: "closed:duplicated"
  - color: f9d0c4
    name: "closed:invalid"
  - color: f9d0c4
    name: "closed:question"
  - color: f9d0c4
    name: "closed:wontfix"
  - color: 7057ff
    name: "good first issue"
  - color: 7057ff
    name: "Hacktoberfest"
  - color: 7057ff
    name: "help wanted"
  - color: cceecc
    name: "status:backlog"
  - color: b60205
    name: "status:block-merge"
  - color: b60205
    name: "status:blocked"
  - color: 0e8a16
    name: "status:in-progress"
  - color: 0e8a16
    name: "status:merge-when-green"
  - color: fbca04
    name: "status:needs-backport"
  - color: fbca04
    name: "status:needs-forwardport"
  - color: fbca04
    name: "status:needs-info"
  - color: fbca04
    name: "status:needs-verification"
  - color: 0e8a16
    name: "status:ready"
  - color: fbca04
    name: "status:to-review"
  - color: c5def5
    name: "topic:build/tests"
  - color: c5def5
    name: "topic:dev-environment"
  - color: c5def5
    name: "topic:documentation"
  - color: c5def5
    name: "topic:jdk-next"
  - color: b60205
    name: "type:defect"
  - color: 0052cc
    name: "type:feature"
  - color: 0052cc
    name: "type:improvement"
  - color: 0052cc
    name: "type:updates"
  - color: bf0d92
    name: "type:template-control"
