package com.example.filedownload.impl

import java.net.InetAddress

import com.example.filedownload.api.Employee

import scala.concurrent.Future

class EmployeeRepository {

  // In a real application, this might use a database,
  // but for this example it's a hard coded list.
  def allEmployees(): Future[List[Employee]] = Future.successful(EmployeeRepository.Employees)

}

object EmployeeRepository {

  // Generated by https://mockaroo.com/
  final val Employees = List(
    Employee(1, "Hugh", "Mariet", "hmariet0@furl.net", "Youspan", InetAddress.getByName("11.100.203.35")),
    Employee(2, "Margaux", "Cuolahan", "mcuolahan1@ameblo.jp", "Fivebridge", InetAddress.getByName("106.4.10.220")),
    Employee(3, "Raquel", "Ancell", "rancell2@unblog.fr", "Babbleset", InetAddress.getByName("197.43.164.85")),
    Employee(4, "Lory", "Gronow", "lgronow3@meetup.com", "Dabjam", InetAddress.getByName("3.46.201.18")),
    Employee(5, "Leanora", "Sherratt", "lsherratt4@nasa.gov", "Yambee", InetAddress.getByName("155.58.57.244")),
    Employee(6, "Kym", "Gorges", "kgorges5@pagesperso-orange.fr", "Devshare", InetAddress.getByName("246.138.230.248")),
    Employee(7, "Terrill", "Lantoph", "tlantoph6@stumbleupon.com", "Latz", InetAddress.getByName("119.135.46.115")),
    Employee(8, "Paten", "Iremonger", "piremonger7@vinaora.com", "Janyx", InetAddress.getByName("72.134.57.90")),
    Employee(9, "Georas", "Tidcomb", "gtidcomb8@mysql.com", "Teklist", InetAddress.getByName("137.7.238.246")),
    Employee(10, "Nealson", "Handrock", "nhandrock9@delicious.com", "Jayo", InetAddress.getByName("201.149.129.191")),
  )

}
