#!/bin/bash

## Based on https://github.com/playframework/play-scala-tls-example/edit/2.5.x/play
## All JVM_XXX options are removed because Lagom does a different handling of SSL
## than Play. Only the ALPN Agent setup is relevant for Lagom.

# ssl-play requires an ALPN Agent. This is downdloaded and stored in the target
# folder of each subproject that needs ALPN enabled.
# This snippet detects when the ALPN agent hasn't been downloaded yet and runs
# `sbt stage` to obtain it.
export AGENT_TEST=$(pwd)/$(find . -name 'jetty-alpn-agent-*.jar')
export NUM_AGENTS_FOUND=$(echo $AGENT_TEST| grep target | wc -l)

if [ $NUM_AGENTS_FOUND -eq "0" ]; then
   sbt stage;
fi

# Start `sbt` with the JVM_OPTIONS and the ALPN agent
export AGENT=$(pwd)/$(find . -name 'jetty-alpn-agent-*.jar' | head -1)
echo "Detected ALPN Agent: $AGENT "
export SBT_OPTS="$SBT_OPTS -javaagent:$AGENT"
# Run Play
sbt $JVM_OPTIONS $*;
